### ISSUE TITLE
When I swipe error  occure

### ISSUE THREAD

**Issue by vishalpatel1327** [hudomju/android-swipe-to-dismiss-undo#47]
java.lang.AbstractMethodError: abstract method "void android.support.v7.widget.RecyclerView$OnItemTouchListener.onRequestDisallowInterceptTouchEvent(boolean)"
                                                                                at android.support.v7.widget.RecyclerView.requestDisallowInterceptTouchEvent(RecyclerView.java:2730)
                                                                                at com.hudomju.swipe.adapter.RecyclerViewAdapter.requestDisallowInterceptTouchEvent(RecyclerViewAdapter.java:49)
                                                                                at com.hudomju.swipe.SwipeToDismissTouchListener.onTouch(SwipeToDismissTouchListener.java:329)
                                                                                at android.view.View.dispatchTouchEvent(View.java:8470)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                                at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:2752)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                                at android.view.View.dispatchPointerEvent(View.java:8671)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
                                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
                                                                                at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
                                                                            	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.j

**Comment by dyoburon** [comment]
I have the same error.
